upload:
  upload_dir: "./uploads"
  max_file_size: 104857600  # 100MB
  allowed_extensions:
    - "txt"
    - "pdf"
    - "doc"
    - "docx"
    - "zip"
    - "tar"
    - "gz"
    - "json"
    - "yaml"
    - "yml"
  compression_enabled: true
  backup_enabled: true
  backup_dir: "./backups"

workflow:
  workflow_dir: "./workflows"
  max_concurrent_workflows: 4
  timeout_seconds: 3600  # 1 hour
  retry_attempts: 3

system:
  temp_dir: "./temp"
  cache_dir: "./cache"
  max_memory_usage: 1073741824  # 1GB
  cpu_limit: 0.8  # 80%

logging:
  log_level: "info"
  log_file: "./logs/automation.log"
  enable_console: true
